---
sudo: true
language: python
dist: xenial

install:
  # Install specific version of exiftool
  - wget https://sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-11.11.tar.gz && gzip -dc Image-ExifTool-11.11.tar.gz | tar -xf - && cd Image-ExifTool-11.11 && perl Makefile.PL && sudo make install
  - cd ..
  - sudo rm -f /etc/ImageMagick-6/policy.xml
  - sudo apt-get install xvfb libreoffice libfile-mimeinfo-perl inkscape poppler-utils qpdf imagemagick ufraw-batch -y
  - pip install xvfbwrapper
  - python setup.py install
  - pip install pytest
  - python3 -m pip install -U mypy

# command to run tests
script:
  - "cd ${TRAVIS_BUILD_DIR} && py.test tests"

#  - "cd ${TRAVIS_BUILD_DIR} && mypy preview_generator --ignore-missing-imports --disallow-untyped-defs"

jobs:
  include:
    - stage: static-tests
      name: fmt
      python: "3.7"
      before_script:
        - pip install black isort
      script:
        - black --version
        - echo -n "isort " && isort --version-number
        - black -l 100 --exclude '/(\..*)/' --diff --check preview_generator tests setup.py
        - isort -df -c **/*.py
    - stage: static-tests
      name: flake8
      python: "3.7"
      before_script:
        - pip install flake8
      script:
        - flake8 --version
        - flake8
    - stage: static-tests
      name: mypy
      python: "3.7"
      before_script:
        - pip install mypy
      script:
        - mypy --version
        - mypy --ignore-missing-imports --disallow-untyped-defs .
    - stage: tests
      python: "3.5"
    - stage: tests
      python: "3.6"
    - stage: tests
      python: "3.7"
    - stage: tests
      python: "3.8-dev"

stages:
  - static-tests
  - tests
